[ssh]
bind="127.0.0.1"
port=2222
private_key="/etc/ssh/ssh_host_ed25519_key"
certificate="/etc/ssh/ssh_host_ed25519_key-cert.pub"

[ca]
ca_key="../test_data/test_key"
user_list_file="../test_data/test_key"
default_user_template="../test_data/test_key"
host_inventory="../config/hosts/"


[identity_handlers]
user_authenticators=[
  "pam",
]


